<?php

	namespace Omnipay\iPaymu\Message;

	use Omnipay\Common\Message\AbstractResponse;

	class CompletePurchaseResponse extends AbstractResponse
	{
		public function isSuccessful()
	    {
	        return isset($this->data['status_code']) && (int)$this->data['status_code'] == 1;
	    }

	    /**
	     * Is the response successful?
	     *
	     * @return boolean
	     */
	    public function isPending()
	    {
	        return isset($this->data['status_code']) && (int)$this->data['status_code'] == 0;
	    }

	    /**
	     * Is the transaction cancelled by the user?
	     *
	     * @return boolean
	     */
	    public function isCancelled()
	    {
	        return isset($this->data['status_code']) && (int)$this->data['status_code'] == 2; // NOTE: 2 is "expired"
	    }

	    /**
	     * Response Message
	     *
	     * @return null|string A response message from the payment gateway
	     */
	    public function getMessage()
	    {
	    	if (isset($this->data['status'])){
	    		return $this->data['status'];
	    	}
	    }

	    /**
	     * Response code
	     *
	     * @return null|string A response code from the payment gateway
	     */
	    public function getCode()
	    {
	        if (isset($this->data['status_code'])){
	    		return $this->data['status_code'];
	    	}
	    }

	    /**
	     * Gateway Reference
	     * NOTE: Gateway returns also "sid" (Session ID)
	     *
	     * @return null|string A reference provided by the gateway to represent this transaction
	     */
	    public function getTransactionReference()
	    {
	    	if (isset($this->data['trx_id'])){
	    		return $this->data['trx_id'];
	    	}
	    }

	    /**
	     * Get the transaction ID as generated by the merchant website.
	     *
	     * @return string
	     */
	    /*public function getTransactionId()
	    {
	        
	    }*/
	}