<?php

	namespace Omnipay\iPaymu\Message;

	use Omnipay\Common\Message\AbstractResponse;

	class CompletePurchaseResponse extends AbstractResponse
	{
		/**
	     * Is the payment successful?
	     *
	     * @return boolean
	     */
		public function isSuccessful()
	    {
	        return isset($this->data['status_code']) && (int)$this->data['status_code'] == 1;
	    }

	    /**
	     * Is the payment pending?
	     *
	     * @return boolean
	     */
	    public function isPending()
	    {
	        return isset($this->data['status_code']) && (int)$this->data['status_code'] == 0;
	    }

	    /**
	     * Is the transaction cancelled by the user or expired?
	     *
	     * @return boolean
	     */
	    public function isCancelled()
	    {
	        return isset($this->data['status_code']) && (int)$this->data['status_code'] == -2;
	    }

	    /**
	     * Response Message
	     *
	     * @return null|string A response message from the payment gateway
	     */
	    public function getMessage()
	    {
	    	if (isset($this->data['status'])){
	    		return $this->data['status'];
	    	}
	    }

	    /**
	     * Response code
	     *
	     * @return null|string A response code from the payment gateway
	     */
	    public function getCode()
	    {
	        if (isset($this->data['status_code'])){
	    		return $this->data['status_code'];
	    	}
	    }

	    /**
	     * Gateway Reference
	     *
	     * @return null|string A reference provided by the gateway to represent this transaction
	     */
	    public function getTransactionReference()
	    {
	    	if (isset($this->data['trx_id'])){
	    		return $this->data['trx_id'];
	    	}

	    	return null;
	    }

	    /**
	     * Get the transaction ID as generated by the merchant website.
	     *
	     * @return string
	     */
	    public function getTransactionId()
	    {
	        if (isset($this->data['reference_id'])){
	    		return $this->data['reference_id'];
	    	}
	    }

	    /**
	     * Get the session ID (used only in payment redirect method)
	     *
	     * @return string
	     */
	    public function getSessionId()
	    {
	        if (isset($this->data['sid'])){
	    		return $this->data['sid'];
	    	}
	    }
	}